version: "3.8"
services:
  req-printer:
    build: .
    command: gin --immediate --path /app go run main.go
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PRETTY_HEADER=false
      - PRETTY_PAYLOAD=false
    ports:
      - "8090:80"